import type { Status } from "../components/StatusBadge";

export const routeStatus: Record<string, Status> = {
  "/": "ready",
  "/dashboard": "ready",
  "/login": "ready",
  "/signup": "ready",
  "/guest": "ready",
  "/tasks/:projectId": "ready",
  "/alltasks": "ready",
  "/tasks-delta": "ready",
  "/projects-delta": "ready",
  "/tasks/new": "ready",
  "/reports": "ready",
  "/project/:projectId": "ready",
  "/task/:taskId": "ready",
  "/request-project": "ready",
  "/audit-log": "ready",
  "/intake": "ready",
  "/team": "ready",
  "/archive": "ready",
  "/admin/rbac": "ready",
  "/admin/decisions": "ready",
  "/admin/court-flow": "ready",
  "/leaderboard": "ready",
  "/velocity": "ready",
  "/profile": "ready",
  "/incidents": "ready",
  "/incidents/:id": "ready",
  "/showcase": "ready",
  "/styleguide": "ready",
  "/about/eden": "ready",
  "/routes": "ready",
  "/ops/routes": "ready",
};
