# GitHub Actions Workflow for Navigation Smoke Test
# Add this to .github/workflows/smoke-test.yml

name: Navigation Smoke Test

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install root dependencies
        run: npm ci
      
      - name: Install frontend dependencies
        run: |
          cd apps/coordination_ui
          npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Set environment variables
        run: |
          echo "BASE_URL=http://localhost:5000" >> $GITHUB_ENV
          echo "NODE_ENV=test" >> $GITHUB_ENV
      
      # Optional: Provide test credentials for authenticated smoke tests
      # This allows testing protected routes without auth redirects
      - name: Set Playwright credentials (if available)
        if: ${{ secrets.PW_EMAIL != '' && secrets.PW_PASSWORD != '' }}
        run: |
          echo "PW_EMAIL=${{ secrets.PW_EMAIL }}" >> $GITHUB_ENV
          echo "PW_PASSWORD=${{ secrets.PW_PASSWORD }}" >> $GITHUB_ENV
      
      - name: Run navigation smoke test
        run: npm run test:smoke
      
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: coverage/playwright-report
          retention-days: 7
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7

# Setting up secrets:
# 1. Go to: Repository Settings → Secrets and variables → Actions
# 2. Add repository secret: PW_EMAIL = test@edenplumbing.com
# 3. Add repository secret: PW_PASSWORD = <your test user password>
# 
# Without secrets:
# - Tests run unauthenticated
# - Protected routes redirect to /login (expected)
# - Tests verify login page renders correctly
# 
# With secrets:
# - Tests run authenticated
# - Protected routes render actual content
# - Full UI validation of all features
