name: Quality Gates

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  gates:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Ensure contract-driven showcase (and other generators) run before builds/tests
      - name: Build (all)
        run: |
          npm run build -w apps/coordination_ui || npm run build

      - name: UI coverage
        run: npm run check:ui

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Smoke navigation (contract-driven)
        env:
          # Optional secrets for auth-aware run; omit if not set
          PW_EMAIL: ${{ secrets.PW_EMAIL }}
          PW_PASSWORD: ${{ secrets.PW_PASSWORD }}
          BASE_URL: http://localhost:4173
        run: npm run test:smoke

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: coverage/playwright-report

      - name: Upload UI gaps (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-gaps
          path: coverage/ui-gaps.*
          if-no-files-found: ignore
